const demoListings = [
  {
    seed_key: "demo-seat-leon-mk3-right-headlight",
    title: "Seat Leon Mk3 Right Headlight 2012-2020 LED",
    part_type: "headlight",
    category: "lighting",
    make: "Seat",
    model: "Leon Mk3",
    year: "2012-2020",
    side: "right",
    condition: "Used, good - light marks",
    part_number: null,
    colour: null,
    engine_size: null,
    location: "Demo inventory",
    confidence: 95,
    image_url: "/demo-listings/seat-leon-mk3-right-headlight.png",
  },
  {
    seed_key: "demo-seat-leon-mk3-right-fog-light-cover",
    title: "Seat Leon Mk3 Right Fog Light Cover Trim 2012-2020",
    part_type: "fog light cover",
    category: "bodywork",
    make: "Seat",
    model: "Leon Mk3",
    year: "2012-2020",
    side: "right",
    condition: "Used, good - light marks",
    part_number: null,
    colour: "black",
    engine_size: null,
    location: "Demo inventory",
    confidence: 96,
    image_url: "/demo-listings/seat-leon-mk3-right-fog-light-cover.png",
  },
  {
    seed_key: "demo-volkswagen-golf-polo-mk8-2022-headlight",
    title: "Volkswagen Golf Polo Mk8 2022+ Headlight LED",
    part_type: "headlight",
    category: "lighting",
    make: "Volkswagen",
    model: "Golf / Polo Mk8",
    year: "2022+",
    side: null,
    condition: "Used, good - visible marks",
    part_number: null,
    colour: null,
    engine_size: null,
    location: "Demo inventory",
    confidence: 90,
    image_url: "/demo-listings/volkswagen-golf-polo-mk8-2022-headlight.png",
  },
  {
    seed_key: "demo-pagid-jeep-brake-disc",
    title: "Pagid Jeep Front Brake Disc Vented",
    part_type: "brake disc",
    category: "braking",
    make: "Jeep",
    model: null,
    year: null,
    side: "front",
    condition: "New or unused demo stock",
    part_number: null,
    colour: null,
    engine_size: null,
    location: "Demo inventory",
    confidence: 92,
    image_url: "/demo-listings/pagid-jeep-brake-disc.png",
  },
  {
    seed_key: "demo-bmw-m3-brake-discs",
    title: "BMW M3 Front Brake Discs Pair Drilled",
    part_type: "brake disc",
    category: "braking",
    make: "BMW",
    model: "M3",
    year: null,
    side: "front",
    condition: "Used, good - pair",
    part_number: null,
    colour: null,
    engine_size: null,
    location: "Demo inventory",
    confidence: 94,
    image_url: "/demo-listings/bmw-m3-brake-discs.png",
  },
];

module.exports = {
  demoListings,
};
